services:
  postgres:
    image: postgres:15-alpine
    container_name: twitter_clone_postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'twitter_clone'
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    image: node:18-alpine
    container_name: twitter_clone_backend
    working_dir: /usr/src/app
    depends_on:
      - postgres
    environment:
      NODE_ENV: local
      APP_PORT: 3000
      API_PREFIX: /trpc
      SECRET_KEY: supersecret
      JWT_EXPIRES_IN: 1d
      DATABASE_URL: postgresql://user:password@postgres:5432/twitter_clone?schema=public
    volumes:
      - ..:/usr/src/app
    command: sh -c "apk add --no-cache openssl && npm install --legacy-peer-deps && npx prisma migrate deploy && npx prisma generate && npm run backend:dev"
    ports:
      - 3000:3000

  frontend:
    image: node:18-alpine
    container_name: twitter_clone_frontend
    working_dir: /usr/src/app
    depends_on:
      - backend
    environment:
      VITE_APP_URL: http://localhost:3000/trpc
      DATABASE_URL: postgresql://user:password@postgres:5432/twitter_clone?schema=public
    volumes:
      - ..:/usr/src/app
    command: sh -c "apk add --no-cache openssl && npm install --legacy-peer-deps && npm run frontend:dev"
    ports:
      - 4200:4200

volumes:
  postgres:
